### ISSUE TITLE
Side bar in Home view is too small

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/MicroMetaExplorer#20]
The side bar is too small and the names of categories spill over

![image](https://github.com/WU-BIMAC/MicroMetaExplorer/assets/4050585/232a70e2-842c-40b2-b129-0ac43da5d33b)

Solution: expand size to include all categories sizes available

**Comment by Akramhar** [comment]
This should be fixed in MME 1.1.0-b1

**Comment by strambc** [comment]
Much better but could you please consider the change suggested in the screenshot?

<img width="570" height="840" alt="Image" src="https://github.com/user-attachments/assets/cba0a652-27eb-45c7-9192-efa77d5ee2e3" />

**Comment by Akramhar** [comment]
should be solved in mma 1.8.2, explorer 1.1.2, mmt 2.2.2

**Comment by strambc** [comment]
Change in the screenshot was not implemented

**Comment by strambc** [comment]
Not solved. Text should wrap after 28 characters (see screen shot).

**Comment by Akramhar** [comment]
should be solved in mme 1.1.4, explorer 2.2.4
